config/routes.rb
MainProject::Application.routes.draw do
  
  resources :unebs

  resources :notes

  resources :students

  resources :teachers

  resources :roles

  

  root :to =>"main#index"
  match 'admin', :to=>"sessions#menu"
  

  resources :subjects

  resources :schools

  resources :users

  match ':controller(/:action(/:id))(.:format)'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
has_and_belongs_to_many :roles
  
  scope :sorted, order('permissions.id ASC')
end

app/models/role.rb
class Role < ActiveRecord::Base
has_and_belongs_to_many :permissions
  has_many :users
  
  validates_presence_of :title
  validates :description, :presence => true
end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :subscriber

	validates :schoolname, :presence=>true, :uniqueness=>true
	validates :address, :presence=>true
	validates :headteacher, :presence=>true
end

app/models/student.rb
class Student < ActiveRecord::Base
	validates :firstname, :lastname, :parent_name, :phone_number, :address, :presence=>true
	validates :student_number, :presence=>true, :uniqueness=>true
	validates :student_school, :student_class, :presence=>true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	validates :subjectname, :presence=>true, :uniqueness=>true
	validates :subjectlevel, :presence=>true
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/models/uneb.rb
class Uneb < ActiveRecord::Base
	
	#has_attached_file :app
	attr_accessor :app

	validates :subject, :presence=>true
	#validates_attachment_presence :app
	#validates_attachment_content_type :app, :content_type => ['file/pdf', 'file/docx']

	def self.save(upload)
		name1 =  upload['datafile'].original_filename
		directory = "assets/unebpapers"
		# create the file path
		path = File.join(directory, name1)
		# write the file
		File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	require 'digest/sha2'
	
	EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9._]+\.[A-Z]{2,4}$/i

	validates :username, :presence => true , :uniqueness => true
	validates :firstname, :presence => true
	validates :lastname, :presence => true
	validates :phone_number, :presence => true
	validates :password, :confirmation => true
	validates :email, :presence=> true,:length=>{:maximum=>100}, :format=>EMAIL_REGEX,:confirmation=>true

	attr_accessor :password_confirmation
	attr_reader :password

	validate :password_must_be_present

	def User.authenticate(username, password)
		if user = find_by_username(username)
			if user.hashed_password == encrypt_password(password, user.salt)
				user
			end
		end
	end

	def User.encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end

	def password=(password)
		@password = password
		if password.present?
			generate_salt
			self.hashed_password = self.class.encrypt_password(password, salt)
		end	
	end	

	private

	def password_must_be_present
		errors.add(:password, "Missing Password") unless hashed_password.present?
	end

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end
end

app/controllers/unebs_controller.rb
class UnebsController < ApplicationController
  # GET /unebs
  # GET /unebs.json
  layout 'admin'
  before_filter :confirm_logged_in
  
  def index
    @unebs = Uneb.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @unebs }
    end
  end

  # GET /unebs/1
  # GET /unebs/1.json
  def show
    @uneb = Uneb.find(params[:id])
    @subjects=Subject.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @uneb }
    end
  end

  # GET /unebs/new
  # GET /unebs/new.json
  def new
    @uneb = Uneb.new
    @subjects=Subject.order('subjects.subjectname')
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @uneb }
    end
  end

  # GET /unebs/1/edit
  def edit
    @uneb = Uneb.find(params[:id])
    @subjects=Subject.all
  end
  def uploadFile
    post =DataFile.save(params[:upload])
    flash[:notice]="File has been successfully Uploaded"
     # render :text => "File has been successfully Uploaded"
  end
  # POST /unebs
  # POST /unebs.json
  def create
    @uneb = Uneb.new(params[:uneb])
    @subjects=Subject.all
    respond_to do |format|
      if @uneb.save
        format.html { redirect_to @uneb, notice: 'Uneb was successfully created.' }
        format.json { render json: @uneb, status: :created, location: @uneb }
      else
        format.html { render action: "new" }
        format.json { render json: @uneb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /unebs/1
  # PUT /unebs/1.json
  def update
    @uneb = Uneb.find(params[:id])
    @subjects=Subject.all
    if @uneb.update_attributes(params[:unebs])
      flash[:notice]="paper successfully updated"
      redirect_to :action=>'index'
    else
      flash[:notice]="Failed to update"
      render :action=>'edit'
    end
  end

  # DELETE /unebs/1
  # DELETE /unebs/1.json
  def destroy
    @uneb = Uneb.find(params[:id])
    @uneb.destroy

    respond_to do |format|
      format.html { redirect_to unebs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/unebs_helper.rb
module UnebsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/unebs/_form.html.erb
  <% if @uneb.errors.any? %>
    <div  id="error_explanation" style="border:1px solid black;border-color:#CC0000; font-size:14px;text-align:left;">
      <% @uneb.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
    </div>
  <% end %>
  <table>   
    
    <div class="field">
      <tr><td>
      <%= f.label :subject_name %></td><td>
      <%= f.select(:subject, @subjects.collect {|r| [r.subjectname]}, {:include_blank=>"--- select subject ---"}) %>
      </td></tr>
    </div>
    <div class="field">
      <tr><td>
      <%= f.label :academic_level %></td><td>
      <%= f.text_field :academic_level %>
      </td></tr>
    </div>
    <div class="field">
      <tr><td>
      <%= f.label :file %></td><td>
      <%= f.file_field :app %>
      </td></tr>
    </div>
    <div class="field">
      <tr><td>
      <%= f.label :academic_year %></td><td style="width:500px;">
      <%= f.date_select :academic_year %>
    </td></tr>
    </div>
    <div class="actions">
      <tr><td>
      <%= submit_tag "Upload", :class=>"btn btn-medium btn-success" %>
      </td></tr>
    </div>
  
</table>

app/views/unebs/edit.html.erb
<h3>Editing uneb</h3>

<%= form_for(:uneb, :url=>{:action=>'update', :id=>@uneb.id}, :html=>{:multipart=>true}) do |f| %>
<%= render(:partial=>'form', :locals=>{:f=>f}) %>

<% end %>

<%= link_to 'Show', @uneb , :class=>"btn-link"%> |
<%= link_to 'Back', unebs_path, :class=>"btn-link" %>

app/views/unebs/index.html.erb
<h3>Listing unebs</h3>

<table class="table table-striped" style="font-size:14px;">
  <tr>
    <th>Academic year</th>
    <th>Subject</th>
    <th>Academic level</th>    
    <th>Action</th>
  </tr>

<% @unebs.each do |uneb| %>
  <tr>
    <td><%= uneb.academic_year %></td>
    <td><%= uneb.subject %></td>
    <td><%= uneb.academic_level %></td>
    <td><%= link_to 'Show', uneb , :class=>"btn-link"%> |
        <%= link_to('Edit', {:action=>'edit', :id=>uneb.id}, :class=>"btn-link") %> |
        <%= link_to 'Destroy', uneb, confirm: 'Are you sure?', method: :delete, :class=>"btn-link" %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Uneb', new_uneb_path , :class=>"btn btn-medium btn-info"%>

app/views/unebs/new.html.erb
<h3>New uneb paper</h3>
<%= form_for(:uneb, :url=>{:action=>'create'}, :html=>{:multipart=>true}) do |f| %>
<%= render(:partial=>'form', :locals=>{:f=>f}) %>

<% end %>
<%= link_to 'Back', unebs_path , :class=>"btn-link"%>

app/views/unebs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Academic year:</b>
  <%= @uneb.academic_year %>
</p>

<p>
  <b>Subject:</b>
  <%= @uneb.subject %>
</p>

<p>
  <b>Academic level:</b>
  <%= @uneb.academic_level %>
</p>

<p>
  <b>App file name:</b>
  <%= @uneb.app_file_name %>
</p>

<p>
  <b>App file size:</b>
  <%= @uneb.app_file_size %>
</p>

<p>
  <b>App content type:</b>
  <%= @uneb.app_content_type %>
</p>


<%= link_to 'Edit', edit_uneb_path(@uneb) %> |
<%= link_to 'Back', unebs_path %>