config/routes.rb
MainProject::Application.routes.draw do
  
  resources :unebs

  resources :notes

  resources :students

  resources :teachers

  resources :roles

  

  root :to =>"main#index"
  match 'admin', :to=>"sessions#menu"
  

  resources :subjects

  resources :schools

  resources :users

  match ':controller(/:action(/:id))(.:format)'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
has_and_belongs_to_many :roles
  
  scope :sorted, order('permissions.id ASC')
end

app/models/role.rb
class Role < ActiveRecord::Base
has_and_belongs_to_many :permissions
  has_many :users
  
  validates_presence_of :title
  validates :description, :presence => true
end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :subscriber

	validates :schoolname, :presence=>true, :uniqueness=>true
	validates :address, :presence=>true
	validates :headteacher, :presence=>true
end

app/models/student.rb
class Student < ActiveRecord::Base
	validates :firstname, :lastname, :parent_name, :phone_number, :address, :presence=>true
	validates :student_number, :presence=>true, :uniqueness=>true
	validates :student_school, :student_class, :presence=>true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	validates :subjectname, :presence=>true, :uniqueness=>true
	validates :subjectlevel, :presence=>true
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/models/uneb.rb
class Uneb < ActiveRecord::Base
	
	#has_attached_file :app
	attr_accessor :app

	validates :subject, :presence=>true
	#validates_attachment_presence :app
	#validates_attachment_content_type :app, :content_type => ['file/pdf', 'file/docx']

	def self.save(upload)
		name1 =  upload['datafile'].original_filename
		directory = "assets/unebpapers"
		# create the file path
		path = File.join(directory, name1)
		# write the file
		File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	require 'digest/sha2'
	
	EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9._]+\.[A-Z]{2,4}$/i

	validates :username, :presence => true , :uniqueness => true
	validates :firstname, :presence => true
	validates :lastname, :presence => true
	validates :phone_number, :presence => true
	validates :password, :confirmation => true
	validates :email, :presence=> true,:length=>{:maximum=>100}, :format=>EMAIL_REGEX,:confirmation=>true

	attr_accessor :password_confirmation
	attr_reader :password

	validate :password_must_be_present

	def User.authenticate(username, password)
		if user = find_by_username(username)
			if user.hashed_password == encrypt_password(password, user.salt)
				user
			end
		end
	end

	def User.encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end

	def password=(password)
		@password = password
		if password.present?
			generate_salt
			self.hashed_password = self.class.encrypt_password(password, salt)
		end	
	end	

	private

	def password_must_be_present
		errors.add(:password, "Missing Password") unless hashed_password.present?
	end

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json
  layout 'admin'
  before_filter :confirm_logged_in
  
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/unebs_helper.rb
module UnebsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :academic_class %><br />
    <%= f.text_field :academic_class %>
  </div>
  <div class="field">
    <%= f.label :app_file_name %><br />
    <%= f.text_field :app_file_name %>
  </div>
  <div class="field">
    <%= f.label :app_file_size %><br />
    <%= f.number_field :app_file_size %>
  </div>
  <div class="field">
    <%= f.label :app_content_type %><br />
    <%= f.text_field :app_content_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Subject</th>
    <th>Academic class</th>
    <th>App file name</th>
    <th>App file size</th>
    <th>App content type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.title %></td>
    <td><%= note.subject %></td>
    <td><%= note.academic_class %></td>
    <td><%= note.app_file_name %></td>
    <td><%= note.app_file_size %></td>
    <td><%= note.app_content_type %></td>
    <td><%= link_to 'Show', note %></td>
    <td><%= link_to 'Edit', edit_note_path(note) %></td>
    <td><%= link_to 'Destroy', note, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @note.title %>
</p>

<p>
  <b>Subject:</b>
  <%= @note.subject %>
</p>

<p>
  <b>Academic class:</b>
  <%= @note.academic_class %>
</p>

<p>
  <b>App file name:</b>
  <%= @note.app_file_name %>
</p>

<p>
  <b>App file size:</b>
  <%= @note.app_file_size %>
</p>

<p>
  <b>App content type:</b>
  <%= @note.app_content_type %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>