config/routes.rb
MainProject::Application.routes.draw do
  
  resources :unebs

  resources :notes

  resources :students

  resources :teachers

  resources :roles

  

  root :to =>"main#index"
  match 'admin', :to=>"sessions#menu"
  

  resources :subjects

  resources :schools

  resources :users

  match ':controller(/:action(/:id))(.:format)'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
has_and_belongs_to_many :roles
  
  scope :sorted, order('permissions.id ASC')
end

app/models/role.rb
class Role < ActiveRecord::Base
has_and_belongs_to_many :permissions
  has_many :users
  
  validates_presence_of :title
  validates :description, :presence => true
end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :subscriber

	validates :schoolname, :presence=>true, :uniqueness=>true
	validates :address, :presence=>true
	validates :headteacher, :presence=>true
end

app/models/student.rb
class Student < ActiveRecord::Base
	validates :firstname, :lastname, :parent_name, :phone_number, :address, :presence=>true
	validates :student_number, :presence=>true, :uniqueness=>true
	validates :student_school, :student_class, :presence=>true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	validates :subjectname, :presence=>true, :uniqueness=>true
	validates :subjectlevel, :presence=>true
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/models/uneb.rb
class Uneb < ActiveRecord::Base
	
	#has_attached_file :app
	attr_accessor :app

	validates :subject, :presence=>true
	#validates_attachment_presence :app
	#validates_attachment_content_type :app, :content_type => ['file/pdf', 'file/docx']

	def self.save(upload)
		name1 =  upload['datafile'].original_filename
		directory = "assets/unebpapers"
		# create the file path
		path = File.join(directory, name1)
		# write the file
		File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	require 'digest/sha2'
	
	EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9._]+\.[A-Z]{2,4}$/i

	validates :username, :presence => true , :uniqueness => true
	validates :firstname, :presence => true
	validates :lastname, :presence => true
	validates :phone_number, :presence => true
	validates :password, :confirmation => true
	validates :email, :presence=> true,:length=>{:maximum=>100}, :format=>EMAIL_REGEX,:confirmation=>true

	attr_accessor :password_confirmation
	attr_reader :password

	validate :password_must_be_present

	def User.authenticate(username, password)
		if user = find_by_username(username)
			if user.hashed_password == encrypt_password(password, user.salt)
				user
			end
		end
	end

	def User.encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end

	def password=(password)
		@password = password
		if password.present?
			generate_salt
			self.hashed_password = self.class.encrypt_password(password, salt)
		end	
	end	

	private

	def password_must_be_present
		errors.add(:password, "Missing Password") unless hashed_password.present?
	end

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # GET /subjects
  # GET /subjects.json
  layout 'admin'
  def index
    @subjects = Subject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject = Subject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @subject = Subject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(params[:subject])

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render json: @subject, status: :created, location: @subject }
      else
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/unebs_helper.rb
module UnebsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation" style="border:1px solid black;border-color:#CC0000; font-size:14px;text-align:left;">
      <% @subject.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
    </div>
  <% end %>
  <table>
  <div class="field">
    <tr><td>
      <%= f.label :subjectname %>
      <%= f.text_field :subjectname %>
    </td></tr>
  </div>
  <div class="field">
    <tr><td>
      <%= f.label :subjectlevel %>
      <%= f.text_field :subjectlevel %>
    </td></tr>
  </div>
  <div class="actions">
    <tr><td>
      <%= submit_tag 'Create subject', :class=>"btn btn-medium btn-success"  %>
    </td></tr>
  </div>
<% end %>
</table>

app/views/subjects/edit.html.erb
<% @page_title = "Subject|Edit" %>
<h3>Editing subject</h3>

<%= render 'form' %>

<%= link_to 'Show', @subject, :class=>"btn-link"  %> |
<%= link_to 'Back', subjects_path, :class=>"btn-link"  %>

app/views/subjects/index.html.erb
<% @page_title = "Subjects|List" %>
<h3>Listing subjects</h3>

<table class="table table-striped" style="font-size:14px;">
  <tr>
    <th>SUBJECT NAME</th>
    <th>SUBJECT LEVEL</th>
    <th>ACTION</th>
  </tr>

<% @subjects.each do |subject| %>
  <tr>
    <td><%= subject.subjectname %></td>
    <td><%= subject.subjectlevel %></td>
    <td><%= link_to 'Show', subject, :class=>"btn-link"  %> |
        <%= link_to 'Edit', edit_subject_path(subject), :class=>"btn-link"  %> |
        <%= link_to 'Destroy', subject, confirm: 'Are you sure?', method: :delete, :class=>"btn-link"  %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subject', new_subject_path , :class=>"btn btn-medium btn-info"%>

app/views/subjects/new.html.erb
<% @page_title = "Subjects|New" %>
<h3>New subject</h3>

<%= render 'form' %>

<%= link_to 'Back', subjects_path, :class=>"btn-link"  %>

app/views/subjects/show.html.erb
<% @page_title = "Subjects|show" %>
<p id="notice"><%= notice %></p>

<p>
  <b>Subjectname:</b>
  <%= @subject.subjectname %>
</p>

<p>
  <b>Subjectlevel:</b>
  <%= @subject.subjectlevel %>
</p>


<%= link_to 'Edit', edit_subject_path(@subject),:class=>"btn-link" %> |
<%= link_to 'Back', subjects_path,:class=>"btn-link" %>