config/routes.rb
MainProject::Application.routes.draw do
  
  resources :unebs

  resources :notes

  resources :students

  resources :teachers

  resources :roles

  

  root :to =>"main#index"
  match 'admin', :to=>"sessions#menu"
  

  resources :subjects

  resources :schools

  resources :users

  match ':controller(/:action(/:id))(.:format)'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/models/permission.rb
class Permission < ActiveRecord::Base
has_and_belongs_to_many :roles
  
  scope :sorted, order('permissions.id ASC')
end

app/models/role.rb
class Role < ActiveRecord::Base
has_and_belongs_to_many :permissions
  has_many :users
  
  validates_presence_of :title
  validates :description, :presence => true
end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :subscriber

	validates :schoolname, :presence=>true, :uniqueness=>true
	validates :address, :presence=>true
	validates :headteacher, :presence=>true
end

app/models/student.rb
class Student < ActiveRecord::Base
	validates :firstname, :lastname, :parent_name, :phone_number, :address, :presence=>true
	validates :student_number, :presence=>true, :uniqueness=>true
	validates :student_school, :student_class, :presence=>true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	validates :subjectname, :presence=>true, :uniqueness=>true
	validates :subjectlevel, :presence=>true
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/models/uneb.rb
class Uneb < ActiveRecord::Base
	
	#has_attached_file :app
	attr_accessor :app

	validates :subject, :presence=>true
	#validates_attachment_presence :app
	#validates_attachment_content_type :app, :content_type => ['file/pdf', 'file/docx']

	def self.save(upload)
		name1 =  upload['datafile'].original_filename
		directory = "assets/unebpapers"
		# create the file path
		path = File.join(directory, name1)
		# write the file
		File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	require 'digest/sha2'
	
	EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9._]+\.[A-Z]{2,4}$/i

	validates :username, :presence => true , :uniqueness => true
	validates :firstname, :presence => true
	validates :lastname, :presence => true
	validates :phone_number, :presence => true
	validates :password, :confirmation => true
	validates :email, :presence=> true,:length=>{:maximum=>100}, :format=>EMAIL_REGEX,:confirmation=>true

	attr_accessor :password_confirmation
	attr_reader :password

	validate :password_must_be_present

	def User.authenticate(username, password)
		if user = find_by_username(username)
			if user.hashed_password == encrypt_password(password, user.salt)
				user
			end
		end
	end

	def User.encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end

	def password=(password)
		@password = password
		if password.present?
			generate_salt
			self.hashed_password = self.class.encrypt_password(password, salt)
		end	
	end	

	private

	def password_must_be_present
		errors.add(:password, "Missing Password") unless hashed_password.present?
	end

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  # GET /teachers
  # GET /teachers.json
  before_filter :confirm_logged_in
layout 'admin'

  def index
    @teachers = Teacher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teachers }
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.json
  def new
    @teacher = Teacher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(params[:teacher])

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render json: @teacher, status: :created, location: @teacher }
      else
        format.html { render action: "new" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.json
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/unebs_helper.rb
module UnebsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
  <div class="field">
    <tr><td>
      <%= f.label :firstname %></td><td>
      <%= f.text_field :firstname %>
    </td></tr>
  </div>
  <div class="field">
    <tr><td>
      <%= f.label :lastname %></td><td>
      <%= f.text_field :lastname %>
    </td></tr>
  </div>
  <div class="field">
    <tr><td>
      <%= f.label :email %></td><td>
      <%= f.text_field :email %>
    </td></tr>
  </div>
  <div class="field">
    <tr><td>
      <%= f.label :phone_number %></td><td>
      <%= f.text_field :phone_number %>
    </td></tr>
  </div>
  <div class="field">
    <tr><td>
      <%= f.label :phone_number %></td><td>
    <%= f.text_field :phone_number %>
    </td></tr>
  </div>
  <div class="field">
    <tr><td>
      <%= f.label :address %></td><td>
      <%= f.text_field :address %>
    </td></tr>
  </div>
  <div class="field">
    <tr><td>
      <%= f.label :school %></td><td>
    <%= f.text_field :school %>
    </td></tr>
  </div>
  <div class="field">
    <tr><td>
      <%= f.label :subject %></td><td>
    <%= f.text_field :subject %>
    </td></tr>
  </div>
  <div class="actions">
    <tr><td>
      <%= submit_tag "Create", :class=>"btn btn-medium btn-success" %>
    </td></tr>
  </div>  
<% end %>
</table>

app/views/teachers/edit.html.erb
<h3>Editing teacher</h3>

<%= render 'form' %>

<%= link_to 'Show', @teacher, :class=>"btn-link" %> |
<%= link_to 'Back', teachers_path, :class=>"btn-link" %>

app/views/teachers/index.html.erb
<h3>Listing teachers</h3>

<table class="table table-striped" style="font-size:14px;">
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Subject</th>
    <th>Action</th>
  </tr>

<% @teachers.each do |teacher| %>
  <tr>
    <td><%= teacher.firstname %></td>
    <td><%= teacher.lastname %></td>
    <td><%= teacher.subject %></td>
    <td>
        <%= link_to 'Show', teacher , :class=>"btn-link" %> |
        <%= link_to 'Edit', edit_teacher_path(teacher), :class=>"btn-link"  %> |
        <%= link_to 'Destroy', teacher, confirm: 'Are you sure?', method: :delete, :class=>"btn-link"  %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Teacher', new_teacher_path , :class=>"btn btn-medium btn-info"%>

app/views/teachers/new.html.erb
<h3>New teacher</h3>

<%= render 'form' %>

<%= link_to 'Back', teachers_path, :class=>"btn-link" %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @teacher.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @teacher.lastname %>
</p>

<p>
  <b>Email:</b>
  <%= @teacher.email %>
</p>

<p>
  <b>Phone number:</b>
  <%= @teacher.phone_number %>
</p>

<p>
  <b>Address:</b>
  <%= @teacher.address %>
</p>

<p>
  <b>School:</b>
  <%= @teacher.school %>
</p>

<p>
  <b>Subject:</b>
  <%= @teacher.subject %>
</p>


<%= link_to 'Edit', edit_teacher_path(@teacher), :class=>"btn-link" %> |
<%= link_to 'Back', teachers_path , :class=>"btn-link" %>